
const styles = {
    appBg: 'bg-[#B9D0AA] p-6 min-h-screen flex justify-center items-center',
    taskItem: "flex items-center justify-between bg-[#F7FCF5] p-3 rounded-xl",
    tag: "px-2 py-1 text-xs rounded-full",
    noTag: "bg-orange-100 text-orange-600",
    tagWork: "bg-blue-100 text-blue-600",
    tagPersonal: "bg-green-100 text-green-600",
    tagOther: "bg-purple-100 text-purple-600",
    taskItemContent: 'flex items-center space-x-2 relative',
    card: "flex items-center justify-center flex-col bg-white p-4 rounded-2xl shadow",
    taskListContainer: "col-span-2 bg-white p-5 rounded-2xl shadow",
    sectionTitle: "text-xl font-bold mb-2",
    largeNumber: "flex items-center justify-center text-3xl font-bold text-yellow-500",
    rootBlockContainer: "grid grid-cols-1 md:grid-cols-3 gap-6 w-full max-w-5xl",
    form: 'flex mb-4',
    input: 'block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 me-2',
    validationErrorMsg: 'text-red-500 text-sm mt-1',
    checkbox: 'form-check-input me-2',
    checkboxChecked: 'line-through text-gray-500',
    modal: 'fixed inset-0 bg-[#DCE7D1] bg-opacity-50 flex items-center justify-center z-50',
    modalContent: 'bg-white rounded-lg shadow-xl p-6 w-full max-w-md mx-auto',
    modalHeader: 'flex justify-between items-center border-b pb-3 mb-4',
    modalTitle: 'text-xl font-semibold text-gray-800',
    modalTextarea: 'w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 mb-4 resize-y h-32',
    modalCloseBtn: 'text-gray-500 hover:text-gray-700 focus:outline-none',
    modalButtons: 'flex justify-end space-x-3',
    addButton: "inline-flex items-center justify-center ml-2 px-4 py-2 font-semibold bg-[#6B8E23] text-white rounded-md shadow-sm hover:bg-[#5C8033] transition",
    buttonFilter: "px-4 py-2 bg-gray-200 rounded-xl",
    buttonPrimary: "mt-2 w-full bg-[#6A97A8] text-white py-2 rounded-xl hover:bg-[#3D5A80] transition",
    buttonPrimaryCalendar: "w-full bg-blue-500 text-white py-2 rounded-xl flex items-center justify-center space-x-2",
    pomodoroButton: "bg-gray-800 text-white px-4 py-2 mt-2 rounded-xl",
    timerButtons: "flex gap-2",
    timerTitle: 'mt-2 text-sm text-gray-600',
    taskButtonContainer: 'flex justify-around mb-2 space-x-2 mt-4',
    tagList: 'absolute top-full left-0 mt-1 bg-white shadow-md rounded-lg z-10'
};

export default styles;
